# SPDX-License-Identifier: 0BSD
# SPDX-FileCopyrightText: The XZ for Java authors and contributors
# SPDX-FileContributor: Lasse Collin <lasse.collin@tukaani.org>

name: Coverity Scan

on:
  push:
    branches: [coverity_scan]

jobs:
  coverity:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Coverity Scan
      uses: vapier/coverity-scan-action@2068473c7bdf8c2fb984a6a40ae76ee7facd7a85 # v1.8.0
      with:
        command: ant
        build_language: java
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
